version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend 
    container_name: react-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
